export const BRAND_PRESETS = [
  {
    id: 'xerox-heat',
    name: 'Xerox Heat',
    description: 'High-contrast poster type with rough club energy',
    identity: {
      displayFont: 'Bebas Neue',
      accent: '#dfff00',
      texture: 'xerox',
      motion: 'jitter',
    },
    settings: {
      effectType: 'vibration',
      blendMode: 'difference',
      color: '#ffffff',
      opacity: 100,
      vibrateSpeed: 45,
      vibrateIntensity: 2,
      blurAmount: 1,
      fontFamily: ['Bebas Neue', 'Bebas Neue', 'Bebas Neue'],
      fontWeight: ['900', '900', '900'],
      fontSize: [140, 110, 88],
      letterSpacing: [-2, -1, 0],
    },
  },
  {
    id: 'wet-chrome',
    name: 'Wet Chrome',
    description: 'Liquid color separation for slow, reflective motion',
    identity: {
      displayFont: 'Anton',
      accent: '#00f0ff',
      texture: 'chrome',
      motion: 'liquid',
    },
    settings: {
      effectType: 'chromatic',
      blendMode: 'screen',
      color: '#ffffff',
      opacity: 100,
      hue: 180,
      blurAmount: 2,
      fontFamily: ['Anton', 'Anton', 'Anton'],
      fontWeight: ['900', '900', '900'],
      fontSize: [132, 108, 84],
      letterSpacing: [-3, -2, -1],
    },
  },
  {
    id: 'acid-office',
    name: 'Acid Office',
    description: 'Fluorescent grid language with sharp flicker',
    identity: {
      displayFont: 'Russo One',
      accent: '#ff00d4',
      texture: 'scanlines',
      motion: 'flicker',
    },
    settings: {
      effectType: 'flicker',
      blendMode: 'difference',
      color: '#dfff00',
      opacity: 100,
      flicker: {
        flickerSpeed: 140,
        flickerIntensity: 25,
        minOpacity: 55,
        maxOpacity: 100,
      },
      fontFamily: ['Russo One', 'Russo One', 'Russo One'],
      fontWeight: ['700', '700', '700'],
      fontSize: [124, 100, 78],
      letterSpacing: [0, 1, 2],
    },
  },
  {
    id: 'blackout-lineup',
    name: 'Blackout Lineup',
    description: 'Oversized title with compact event information',
    identity: {
      displayFont: 'Oswald',
      accent: '#ff3b30',
      texture: 'clean',
      motion: 'slide-up',
    },
    settings: {
      effectType: 'split',
      blendMode: 'normal',
      color: '#ffffff',
      opacity: 100,
      fontFamily: ['Oswald', 'IBM Plex Mono', 'IBM Plex Mono'],
      fontWeight: ['700', '500', '500'],
      fontSize: [156, 42, 34],
      letterSpacing: [-3, 1, 1],
    },
  },
];

export const DEFAULT_BRAND_IDENTITY = {
  displayFont: 'Bebas Neue',
  uiFont: 'Inter',
  metadataFont: 'IBM Plex Mono',
  accent: '#dfff00',
  texture: 'xerox',
  motion: 'jitter',
};
