export const BRAND_PRESETS = [
  {
    id: 'xerox-heat',
    name: 'Xerox Heat',
    description: 'High-contrast poster type with rough club energy',
    identity: {
      displayFont: 'Bebas Neue',
      accent: '#dfff00',
      texture: 'xerox',
      motion: 'jitter',
    },
    settings: {
      effectType: 'vibration',
      blendMode: 'difference',
      color: '#ffffff',
      opacity: 100,
      vibrateSpeed: 45,
      vibrateIntensity: 2,
      blurAmount: 1,
      fontFamily: ['Bebas Neue', 'Bebas Neue', 'Bebas Neue'],
      fontWeight: ['900', '900', '900'],
      fontSize: [140, 110, 88],
      letterSpacing: [-2, -1, 0],
    },
  },
  {
    id: 'wet-chrome',
    name: 'Wet Chrome',
    description: 'Liquid color separation for slow, reflective motion',
    identity: {
      displayFont: 'Anton',
      accent: '#00f0ff',
      texture: 'chrome',
      motion: 'liquid',
    },
    settings: {
      effectType: 'chromatic',
      blendMode: 'screen',
      color: '#ffffff',
      opacity: 100,
      hue: 180,
      blurAmount: 2,
      fontFamily: ['Anton', 'Anton', 'Anton'],
      fontWeight: ['900', '900', '900'],
      fontSize: [132, 108, 84],
      letterSpacing: [-3, -2, -1],
    },
  },
  {
    id: 'acid-office',
    name: 'Acid Office',
    description: 'Fluorescent grid language with sharp flicker',
    identity: {
      displayFont: 'Russo One',
      accent: '#ff00d4',
      texture: 'scanlines',
      motion: 'flicker',
    },
    settings: {
      effectType: 'flicker',
      blendMode: 'difference',
      color: '#dfff00',
      opacity: 100,
      flicker: {
        flickerSpeed: 140,
        flickerIntensity: 25,
        minOpacity: 55,
        maxOpacity: 100,
      },
      fontFamily: ['Russo One', 'Russo One', 'Russo One'],
      fontWeight: ['700', '700', '700'],
      fontSize: [124, 100, 78],
      letterSpacing: [0, 1, 2],
    },
  },
  {
    id: 'blackout-lineup',
    name: 'Blackout Lineup',
    description: 'Oversized title with compact event information',
    identity: {
      displayFont: 'Oswald',
      accent: '#ff3b30',
      texture: 'clean',
      motion: 'slide-up',
    },
    settings: {
      effectType: 'split',
      blendMode: 'normal',
      color: '#ffffff',
      opacity: 100,
      fontFamily: ['Oswald', 'IBM Plex Mono', 'IBM Plex Mono'],
      fontWeight: ['700', '500', '500'],
      fontSize: [156, 42, 34],
      letterSpacing: [-3, 1, 1],
    },
  },
];

export const DEFAULT_BRAND_IDENTITY = {
  displayFont: 'Bebas Neue',
  uiFont: 'Inter',
  metadataFont: 'IBM Plex Mono',
  accent: '#dfff00',
  texture: 'xerox',
  motion: 'jitter',
};

export const TEMPLATE_PRESETS = [
  {
    id: 'event-announcement',
    name: 'Event Announcement',
    description: 'Title, date, and venue hierarchy',
    settings: {
      textLines: ['INSERT', 'FRIDAY 16.01', 'TRAUM CLUB'],
      videoFormat: 'portrait',
      videoWidth: 1080,
      videoHeight: 1350,
      fontSize: [152, 64, 44],
      letterSpacing: [-3, 0, 1],
      textTypes: [],
    },
  },
  {
    id: 'lineup-reveal',
    name: 'Lineup Reveal',
    description: 'Oversized title with stacked artists',
    settings: {
      textLines: ['INSERT', 'ROISS / HANDMADE', 'HET BOS'],
      videoFormat: 'portrait',
      videoWidth: 1080,
      videoHeight: 1350,
      fontSize: [144, 52, 38],
      letterSpacing: [-3, 0, 1],
      textTypes: [],
    },
  },
  {
    id: 'artist-spotlight',
    name: 'Artist Spotlight',
    description: 'One name with supporting metadata',
    settings: {
      textLines: ['INSERT', 'IN_CONSTANT', 'FEATURED MIX'],
      videoFormat: 'square',
      videoWidth: 1080,
      videoHeight: 1080,
      fontSize: [150, 92, 34],
      letterSpacing: [-4, -2, 1],
      textTypes: [],
    },
  },
  {
    id: 'animated-title',
    name: 'Animated Title',
    description: 'Short copy built for motion loops',
    settings: {
      textLines: ['INSERT', 'STAY FOR OVERTIME', 'XXX CREW'],
      videoFormat: 'reels',
      videoWidth: 1080,
      videoHeight: 1920,
      fontSize: [160, 72, 40],
      letterSpacing: [-4, -1, 1],
      textTypes: [],
    },
  },
];

export const PERFORMANCE_PRESETS = [
  {
    id: 'xerox-pulse',
    name: 'Xerox Pulse',
    description: 'Kick-driven threshold, displacement, and feedback',
    settings: {
      scene: 'xerox-pulse',
      energy: 0.7,
      beat: 0.5,
      kick: 0.9,
      warp: 0.35,
      feedback: 0.28,
      chromatic: 0.05,
      seed: 0.12,
    },
  },
  {
    id: 'wet-signal',
    name: 'Wet Signal',
    description: 'Slow liquid distortion with chromatic bloom',
    settings: {
      scene: 'wet-signal',
      energy: 0.55,
      beat: 0.35,
      kick: 0.25,
      warp: 0.62,
      feedback: 0.4,
      chromatic: 0.7,
      seed: 0.3,
    },
  },
  {
    id: 'office-panic',
    name: 'Office Panic',
    description: 'Sharp scanline jumps and short frame holds',
    settings: {
      scene: 'office-panic',
      energy: 0.8,
      beat: 0.7,
      kick: 0.65,
      warp: 0.48,
      feedback: 0.18,
      chromatic: 0.25,
      seed: 0.52,
    },
  },
  {
    id: 'crowd-echo',
    name: 'Crowd Echo',
    description: 'Delayed wordmark layers with scale and opacity decay',
    settings: {
      scene: 'crowd-echo',
      energy: 0.45,
      beat: 0.4,
      kick: 0.3,
      warp: 0.24,
      feedback: 0.62,
      chromatic: 0.18,
      seed: 0.78,
    },
  },
];
